### ISSUE TITLE
Enable to setup a Wipe code

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#10328]
- [x] Prepare wipe code method into connect #10407 
- [x] Enable to setup a wipe code in device settings in danger zone #10434 
- [x] Add option to remove wipe code #10472

**Comment by hynek-jina** [comment]
@STew790 has noticed that there is currently no way how to remove once enabled wipe code.. 👀

**Comment by hynek-jina** [comment]
TODO: add option to remove wipe code (when enabled)

**Comment by bosomt** [comment]
**QA OK**

tested:

- enable
- change
- disable


**Info:**
 - Suite version: desktop 24.1.1 (cd3946024cb2233e2e80788ea25784b83daa0a06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
