### ISSUE TITLE
[EPIC] PIN handling

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#10595]
```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/10596
- [ ] https://github.com/trezor/trezor-suite/issues/10536
- [ ] https://github.com/trezor/trezor-suite/issues/10359
- [ ] https://github.com/trezor/trezor-suite/issues/10538
- [ ] https://github.com/trezor/trezor-suite/pull/11635
```

@trezor/qa please check testing scenarios [in the PR](https://github.com/trezor/trezor-suite/pull/11319)

**Comment by bosomt** [comment]
**QA OK**

24.4.0 (74)
Last commit hash: 2882f42525f5173c6673e0b4c41c9644c2ccb92e
