### ISSUE TITLE
Send Form

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10780]
Issues related to send form

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/7407
- [ ] https://github.com/trezor/trezor-suite/issues/7244
- [ ] https://github.com/trezor/trezor-suite/issues/3283
- [ ] #11037
- [ ] https://github.com/trezor/trezor-suite/pull/11897
```
