### ISSUE TITLE
[Epic]: Add EAS for expo and set up new release process

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10789]
**Set up EAS build**
- [x] Set up EAS build to build android binary
- [x] Set up EAS to build iOS binary
- [x] Submit develop on iOS to testflight
- [x] Submit develop on Android to firebase
- [x] Production for iOS
- [x] Production for Android
- [x] Fix missing build version in About Us screen and do autoincrement
- [x] Env variables not working (commit hash, but also `isDev()` etc)
- [x] Add release notes for android firebase, but consider other flavors and platforms
- [x] `isDev()` condition is not working properly on develop
- [x] We need to discuss how to release app from private repo so we can separate release process from the code
- [x] ad-hoc releases for develop

**Release process revamp**
- [x] Automate process so that we have more frequent and planned releases (unless there is strong reason for not doing a release)
- [ ] Uploading apk to users so they can download it on android without the need for google play #5728
- [ ] Set up feature branch CI so that we can build develop per feature if necessary to test things in between team

**Comment by matejkriz** [comment]
Closing as done, let's create separate issues for specific improvements.
