### ISSUE TITLE
Fiat Rates

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10782]
Issues related to fiat rates

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/10431
- [ ] https://github.com/trezor/trezor-suite/issues/10435
- [x] https://github.com/trezor/trezor-suite/issues/10783
- [x] https://github.com/trezor/trezor-suite/issues/10771
- [x] https://github.com/trezor/trezor-suite/issues/1847
- [ ] https://github.com/trezor/trezor-suite/issues/10464
- [ ] https://github.com/trezor/trezor-suite/issues/10695
- [ ] https://github.com/trezor/trezor-suite/issues/11447
```

**Comment by tomasklim** [comment]
Added #10435 here but not to EVM milestone. Do you think that it makes sense to add it? @AdamSchinzel

**Comment by AdamSchinzel** [comment]
Let's add it 👍
