### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10781]
Issues related to tokens

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/12165
- [ ] https://github.com/trezor/trezor-suite/issues/3883
- [ ] https://github.com/trezor/trezor-suite/issues/11141
- [ ] https://github.com/trezor/trezor-suite/issues/11539
- [ ] https://github.com/trezor/trezor-suite/issues/10912
- [ ] https://github.com/trezor/trezor-suite/issues/11040
```
