### ISSUE TITLE
Solana sign tx modal improvements

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10906]
**Describe the bug**

On Solana, when signing tx, blockhash has to be provided. This blockhash is valid only 150 blocks which is ~60 seconds.

[Design](https://www.figma.com/design/nLpKN2kFcbjZFvyqZ51zgL/Confirm-on-device?node-id=4325-13073&t=xk8BQKxfACUtCQUy-1)

**Expected behavior**
Allow me to send tx, if it fails because of blockhash, I get `retry` button and I can see approximate time I have to confirm the transaction. I want to have there also `retry` button during the signing process in case I know I am slow.

```[tasklist]
### Tasks
- [ ] When opening sign tx modal, fetch new blockhash
- [ ] Introduce timer
- [ ] Introduce retry button which should fetch new blockhash, cancel current device flow and start again
- [ ] Decode/rewrite Solana tx fail notification
- [ ] Introduce retry button if it fails only because of time! not because of something else
- [ ] Update error messages to some human readable text (not "Solana 32000 error")
```

**Screenshots**
In case it takes me too long to confirm transaction on device and I hit `Send`
<img width="691" alt="Image" src="https://github.com/user-attachments/assets/6a25e274-91fc-484f-8822-fefb4643f84c" />

I get into this state with loading. In case I was fast enough and tx is confirmed. Modal is closed and tx is confirmed. Otherwise,...
<img width="693" alt="Image" src="https://github.com/user-attachments/assets/4b82e56c-140b-4954-b5ac-79bc95324ad4" />

I get this error
#15434 
<img width="452" alt="Image" src="https://github.com/user-attachments/assets/7a90aa4a-8848-4ebc-ae17-058a9083d09d" />

**Comment by mroz22** [comment]
not a bug. its a feature of solana 🇸🇧

**Comment by sime** [comment]
Broadcast SOL/all TXs by default?

**Comment by rojcyk** [comment]
@tomasklim Is there a chance to refresh the TX signing modal without the user having to close it and reopening it?

**Comment by tomasklim** [comment]
We can introduce some retry button for solana

**Comment by Ondra-Zik** [comment]
**QA OK**

The timer was introduced to help in these cases, and error messages should also be revamped. all good as long the transaction is confirmed within the timer.  

The retry button is functional in both non-expired trades and expired trades.  

A new block hash is fetched before constructing the transaction.  

The timer is missing in the trade section. The correct error message is being displayed for expired transactions there


**Room for improvement:**  
- Introduce a timer for the trade section.  
- Spamming the retry button can lead to an unpredictable state.  

**Info:**
 - Suite version: desktop 25.3.0 (e816489646dd8cebf27cdff31580a5d6ab8347bc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteLocal/25.3.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.8.9 regular (revision 7614a29c9a9cc138fff446937b7d9489fd57821f)
 - Transport: BridgeTransport 3.0.0-bundled.25.3.0
