### ISSUE TITLE
EPIC - Device images and animations refresh

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11841]
EPIC for images and devices refresh in Q2 2024
```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/11876
- [ ] https://github.com/trezor/trezor-suite/issues/11880
- [ ] https://github.com/trezor/trezor-suite/issues/11881
```

**Comment by MiroslavProchazka** [comment]
Tasks on this epic needs to be tested on special branch in private repository, DM me for more info :)

**Comment by STew790** [comment]
**QA OK**
QA task here https://www.notion.so/satoshilabs/TS5-colors-check-in-Suite-f44643d2ef00475bb8163438a0e5e3c7?pvs=4
