### ISSUE TITLE
EPIC: connect 10 - tracker

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#12710]
Lets start with:
- marking places in code that require refactoring but it comes at the cost of introducing breaking changes with a comment 
```
// todo: connect10
```
- at the same time, if breaking change should be introduced in connect 10, lets put a [deprecation warning](https://github.com/trezor/trezor-suite/issues/12676) where it makes sense.

Lets start listing future breaking changes here:

```[tasklist]
### Future breaking changes
- [ ] remove `connectSettings.webusb`
- [ ] remove workarounds in poup.html (cc @martykan, please edit)
- [ ] device.state string to object - https://github.com/trezor/trezor-suite/pull/12887
- [ ] support native bigint. remove bignumber.js etc where possible
- [ ] remove `TrezorConnect.manifest()`
- [ ] Turn `requestLogin` into a normal method by removing `asyncChallenge`
- [ ] remove `skipPermutation` from `composeTransaction` call (replaced by `sortingStrategy`) https://github.com/trezor/trezor-suite/issues/15070
```

Connect 10 API wish list
- strongly typed errors
- exposed validations? could connect somehow tell its consumers whether the call is allowed and whether it will succeed?

**Comment by szymonlesisz** [comment]
related issue: https://github.com/trezor/trezor-suite/issues/4517

related notes: https://www.notion.so/satoshilabs/Version-10-api-breaking-changes-212426f265074e1ab6651f8ee5096655

**Comment by martykan** [comment]
Closing as we are managing Connect 10 issues separately
