### ISSUE TITLE
Passphrase Authorization during device access on View-Only

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#13291]
Parent issue, mainly for QA purposes. 

Requirements: 
1. When user has a passphrase wallet in view only mode, after reconnecting passphrase isn't requested until the app tries to interact with the device
2. If the app asks for some information from device (add coin account / receive address etc), passphrase should be requested and after success, you should be able to generate receive address or create an account. If wrong passphrase was submitted, user should be alerted 
3. If the device has pin and was locked, then pin should pop-up in the app before passphrase
4. Navigation should behave seamlessly if user cancels this on the device or in app
```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/12689
- [ ] https://github.com/trezor/trezor-suite/issues/12132
- [ ] https://github.com/trezor/trezor-suite/issues/13163
- [ ] https://github.com/trezor/trezor-suite/issues/13191
```
https://www.figma.com/design/mmDnYtctfjnreWhTjLfeQH/Passphrase?node-id=2895-5652&t=WScMaNsEhAqbs34a-0

**Comment by STew790** [comment]
**QA OK**

1. OK
2. OK
3. OK
4. OK

**Info:**
24.6.0 https://github.com/trezor/trezor-suite/commit/ff75009f1076edbd6476b90c97fa899ca7807b48
