### ISSUE TITLE
[epic] connect - mobile support - phase 1

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14248]
Goal: give the 3rd parties the ability to talk to Trezor devices easily.

### Suite-lite as connect provider #13648
- [x] @Nodonisko creates a PR with very basic barebones of the project so that we know where we put our code.
- [x] trezor-suite-lite is capable of handling deep links, which are connect API calls. It hands over such a call to its internal instance of connect and returns the response via a callback URL provided in the link.
- [x] some basic UI within trezor-suite-lite
- [x] there should be a thin package exposing trezor-connect API with deeplinks as the underlying communication mechanism
- [x] example of a client application for demonstration purposes.

### UI-less SDK #13647
we are not sure if want to do it - it would bundle all the expo modules which is probably too heavyweight for 3rd parties to implement. @Nodonisko has some ideas how it could be solved but it is still in the making
- [ ] self-contained within the monorepo structure - I should be able to import and use it. If there is any platform-specific work, it should be documented in a readme file.
- [ ] suite-lite is using this SDK
- [ ] we can run @trezor/connect e2e tests in react-native environment
- consider expo vs non-expo?
- consider #13646
- consider releasing it as an npm package and mentioning it in the public documentation.

## related issues
- URL format spec #14044
 
## team

- @Nodonisko - help with suite-native internals
- @karliatto, @martykan implement the thing

**Comment by Hannsek** [comment]
Let's close this for now, ok?
