### ISSUE TITLE
networksConfig refactoring afterthoughts

### ISSUE THREAD

**Issue by Lemonexe** [trezor/trezor-suite#14445]
Followup to https://github.com/trezor/trezor-suite/issues/13839

Further refactoring of `networksConfig` to reduce information, and make property names clearer.

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/16035
- [ ] https://github.com/trezor/trezor-suite/issues/16034
- [x] https://github.com/trezor/trezor-suite/issues/16271
```
