### ISSUE TITLE
[EPIC] Trezor Suite - Create single source of truth for covered test cases

### ISSUE THREAD

**Issue by HajekOndrej** [trezor/trezor-suite#15020]
Currently we have a page in notion that describes all test cases for Suite and then there are some tests automated in Cypress. This is not great, because someone needs to keep these two places in sync. We should change this and have this in one place. 

I suggest we put all test cases directly to the code, even the manual ones (as skipped).
```[tasklist]
### Tasks
- [x] Map existing tests in web/desktop suite e2e to test cases in sanity template for desktop
- [x] Design how to describe manual as well as automated tests in PW code
- [x] Create a Release reporter https://github.com/trezor/trezor-suite/pull/18505
- [x] Setup the reporter on workflows https://github.com/trezor/trezor-suite/pull/18617
- [x] Expand fields by OS matrix https://github.com/trezor/trezor-suite/pull/18734
- [x] Fix orchestrator https://github.com/trezor/trezor-suite/pull/19173
```
