### ISSUE TITLE
EPIC - ESLint upgrade & refactor

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#15196]
### Main Work

- [x] Upgrade to ESlint 9 https://github.com/trezor/trezor-suite/pull/15287
- [x] Solve: https://www.npmjs.com/package/eslint-plugin-chai-friendly (remove 
- [x] #15297
- [x] https://www.npmjs.com/package/eslint-plugin-jsx-a11y
- [x] #15310
- [x] #15311

### Followup Big Work

- [x] Enable import order for all packaged (get rid of `'import/order': 'off'` in all packages) There is issue for it already https://github.com/trezor/trezor-suite/issues/14031 and PR => https://github.com/trezor/trezor-suite/pull/15264
- [x] Enable all recomanded rules from `jest` plugin https://github.com/trezor/trezor-suite/pull/15158
- [ ] Get rid of `no-restricted-syntax': 'off'` in the `trezor-suite`
- [x] Get rid of `@typescript-eslint/no-unused-vars': "off"` everywhere https://github.com/trezor/trezor-suite/pull/15221
- [ ] Get rid of `import/no-default-export': 'off',` everywhere possible (especially components)
- [x] Get rid of `'@typescript-eslint/no-restricted-imports': 'off',` everywhere https://github.com/trezor/trezor-suite/pull/15245

-------------------

Small PRs to enable some rules that are now recommended:
- [x] `import/no-duplicates` https://github.com/trezor/trezor-suite/pull/15150
- [x] `prefer-const` https://github.com/trezor/trezor-suite/pull/15156
- [x] `no-prototype-builtins` https://github.com/trezor/trezor-suite/pull/15188
- [x] `no-unsafe-optional-chaining` https://github.com/trezor/trezor-suite/pull/15202
- [x] `no-empty` https://github.com/trezor/trezor-suite/pull/15204
- [x] `no-constant-binary-expression` https://github.com/trezor/trezor-suite/pull/15241
- [x] `no-irregular-whitespace` https://github.com/trezor/trezor-suite/pull/15246
- [x] ` no-extra-boolean-cast` https://github.com/trezor/trezor-suite/pull/15260
- [x] `no-async-promise-executor` https://github.com/trezor/trezor-suite/pull/15261
- [x] `no-useless-escape` https://github.com/trezor/trezor-suite/pull/15268
- [x] `no-control-regex` https://github.com/trezor/trezor-suite/pull/15271

-------------------

Small PRs with other fixies:
- https://github.com/trezor/trezor-suite/pull/15220
- https://github.com/trezor/trezor-suite/pull/15225

**Comment by peter-sanderson** [comment]
Most of the work is done, and whats left is waiting for somebody else I guess.
