### ISSUE TITLE
Anonymous mode (via Tor) 🧅

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2445]
Let's implement Anonymous mode (via Tor).

### Desktop
- [x] add switch in options to enable "Tor mode" - [see below](https://github.com/trezor/trezor-suite/issues/2445#issuecomment-718864083)
- [x] indicate Tor mode very vividly (maybe in the title bar?) - [see below](https://github.com/trezor/trezor-suite/issues/2445#issuecomment-718864083)
- [x] finish "application firewall" - block requests going to non-trezor.io domains - PR https://github.com/trezor/trezor-suite/pull/2576
- [x] if running in the "Tor mode", translate all requests going to `https://whatever.trezor.io` to `http://whatever.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion` - PR https://github.com/trezor/trezor-suite/pull/2576
- [x] bundle Tor binaries - PR https://github.com/trezor/trezor-suite/pull/2743
- [x] launch the bundled Tor binaries if no Tor is running - PR https://github.com/trezor/trezor-suite/pull/2576

### Web:
- [x] add detection whether user is currently at `https://suite.trezor.io` or `http://suite.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion` (i.e. "Tor mode" enabled)  - PR https://github.com/trezor/trezor-suite/pull/2576
- [x] if we are in Tor mode and we cannot connect to the bridge, show the instructions how to add the exception (https://wiki.trezor.io/Glossary:Tor) - PR #2576
- [x] add the [onion location](https://community.torproject.org/onion-services/advanced/onion-location/) to meta tags - PR https://github.com/trezor/trezor-suite/pull/2716
- [x] if running in the "Tor mode", translate all requests going to `https://whatever.trezor.io` to `http://whatever.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion` - PR #2576

Note: Tor is not using, https, only http! The traffic is already encrypted and authenticated via Tor network.

**Comment by keraf** [comment]
Just started looking into this. I have some concerns about bundling Tor with Suite:
- I can't find standalone Tor binaries, everything seems to come bundled with TorBrowser.
- Keeping a third-party application up-to-date within Suite is an additional job and responsibility.
- Users who are interested in Tor support might already have it installed.

The approach I would prefer is, when the user wants to enable Tor, check whether Tor is running on the machine or not. If not, we can suggest the user to do so by downloading it from the Tor Project website. If it is running, we can then set Electron to use the Tor proxy.

**Comment by prusnak** [comment]
I agree we should try detecting Tor first, if it is running, use the external instance.

Otherwise we will start the bundled instance, binaries are here:
* https://dist.torproject.org/torbrowser/10.0/tor-win32-0.4.4.5.zip
* https://dist.torproject.org/torbrowser/10.0/tor-win64-0.4.4.5.zip
* https://dist.torproject.org/torbrowser/10.0/tor-linux32-debug.tar.xz
* https://dist.torproject.org/torbrowser/10.0/tor-linux64-debug.tar.xz

(I'll ask the Tor guys, where they store the macOS binaries as they don't seem to be in that folder)

**Comment by prusnak** [comment]
It seems the Tor project does not provide the binaries for general use, and the ones I linked above are mean to be used within the Tor Browser only. :-/

Other option is to use Tor binaries built by Wasabi wallet: https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi/TorDaemons

I will evaluate the options and let you know.

**Comment by keraf** [comment]
@matejzak Do we have some designs for this? For both web and desktop, I think we should display an icon somewhere when it's in Tor mode (like an onion). For desktop only, we should have a place to set the port of the local Tor proxy and a button to switch it on/off.

**Comment by flgh** [comment]
> @matejzak Do we have some designs for this? For both web and desktop, I think we should display an icon somewhere when it's in Tor mode (like an onion). For desktop only, we should have a place to set the port of the local Tor proxy and a button to switch it on/off.

Maybe also an IP field default value=127.0.0.1 for users running tor daemon on another machine ?

**Comment by prusnak** [comment]
> Maybe also an IP field default value=127.0.0.1 for users running tor daemon on another machine ?

Good idea! If it's possible let's make the Tor IP configurable (127.0.0.1 as default). Otherwise, we'll add this in some of the future updates.

**Comment by HikariWS** [comment]
I guess that we can expect Tor users to know how to install it. It's better than having it bundled and get outdated.

Anyway, I'd rather have good old proxy feature. Let us just set our proxy. We can use HTTP or HTTPS for any proxy we have, or SOCKS5 for Tor installed locally or in a LAN server or hidden server anywhere.

I don't run Tor locally anymore, but I used to use Vidalia. It's not maintained anymore but it still works and runs Tor nicely.

**Comment by glacierbits** [comment]
@keraf Design 🎁  

[Navigation](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f6b0073aa3cbd1a4cd1a5af)  
[Settings](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f9ada84ded3b42328e3152d)

**Comment by bosomt** [comment]
**QA OK**

Windows 10
Suite app commit b0dacc3
Device model T FW 2.3.4
