### ISSUE TITLE
Oauth checklist

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2454]
### Dropbox 
- [x] [Implicit flow](https://www.dropbox.com/lp/developers/reference/oauth-guide#implicit-grant) is used (just like in mytrezor) at the moment. Should be migrated to PKCE 
- [x] Legacy long-lived token should not used. Citing from [dropbox docs](https://www.dropbox.com/lp/developers/reference/oauth-guide#) `In the past, the Dropbox API used only long-lived access tokens. These are now deprecated, but will remain available as an option in the Developer console for compatibility until mid 2021.` This affects mytrezor as well.
- [x] Probably ok already, just make sure only App Folder(TREZOR) access is requested, not Full Dropbox access. 

### Google 
- [x] try to use [official lib](https://www.npmjs.com/package/google-auth-library)
- [x] [official docs suggest](https://developers.google.com/identity/protocols/oauth2/native-app) registering electron app as ios app 
- [x] some more read here https://developers.google.com/identity/protocols/oauth2/native-app

### Desktop
- [x] main task here is to keep user credential private so hard requirement here is that installed apps must open the system browser and supply a local redirect URI to handle responses from authorization server.
- [x] response shall be handled by local http server. [Citing google docs:](https://developers.google.com/identity/protocols/oauth2/native-app#uwp) `To receive the authorization code using this URL, your application must be listening on the local web server. That is possible on many, but not all, platforms. However, if your platform supports it, this is the recommended mechanism for obtaining the authorization code.`

### General thoughts
- using refresh token and storing it client side? this is probably the only way how to mantain long-lived flow without need to reauthenticate. If it leakes, it 'only' grants unlimited access to users TREZOR folder with encrypted metadata. So the worst case scenario is that user loses metadata saved there? 
- offline access and refresh token? According to [dropbox docs](https://www.dropbox.com/lp/developers/reference/oauth-guide#) `A client-side web application (pure Javascript)` should `Use the OAuth code flow with short-lived access tokens with PKCE (no refresh tokens).` Or `A client-side Desktop app or mobile app that requires background access` should `
Use the OAuth code flow with PKCE, with refresh tokens` 
- heretic thinking: exposing client_secret. This would allow working with refresh tokens but attacker who gets his hand of refresh token could exchange it for access token and impersonate user (access his trezor folder)

### Some links: 
- https://github.com/openid/AppAuth-JS

**Comment by mroz22** [comment]
OK, I'd say this may be closed now.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0.3 (64-bit)
Suite web dev master commit 43328cf
Device model One FW 1.9.1
