### ISSUE TITLE
NixOS related [tracker]

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2916]
Issue for tracking NixOS related issues:

- [x] https://github.com/trezor/trezor-suite/issues/1578
- [x] https://github.com/trezor/trezor-suite/issues/2614
- [ ]  https://github.com/trezor/trezor-suite/issues/2615
- [x]  https://github.com/trezor/trezor-suite/issues/2921
- [ ]  https://github.com/trezor/trezor-suite/issues/2211
- [x]  ~~https://github.com/trezor/trezor-suite/issues/2962~~ autoupdater is disabled on NixOS
- [x] https://github.com/trezor/trezor-suite/issues/3619

Anything else?

**Comment by prusnak** [comment]
I just packaged Trezor Suite to NixOS via https://github.com/NixOS/nixpkgs/pull/112918

So it is now available via `nix-env -iA unstable.trezor-suite`.

The NixOS package is modified to use NixOS version of `trezord` and `tor` binaries, not the bundled ones.

Also the auto-updater on NixOS is disabled - see https://github.com/trezor/trezor-suite/pull/3290

We can re-retest the reported issues with the NixOS packaged version of the Suite and close them if they are not present anymore.

Since the NixOS package differs from the AppImage package, we should always test Linux releases on more common Linux system (Ubuntu). And instruct NixOS users to not use the AppImage package, but the package provided by the nixpkgs.
