### ISSUE TITLE
Epic: Move Connect to monorepo and refactor it

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#2924]
High level issue for the [trezor-connect](https://github.com/trezor/trezor-connect) work we need to do:

## P1 High:

_Being done by @szymonlesisz._

- [ ] Move to monorepo. create multiple packages: 
    - [x] core (nodejs essential)
    - [x] https://github.com/trezor/trezor-suite/issues/4363
    - [x] UI (landingpage/connect-explorer),
    - [ ] web wrapper(3rd party popup usage),
    - [ ] webextension-background/electron-layer wrapper
- [x] TypeScript support
- [ ] more unit tests (btc-like: ltc, and others supported, errors, invalid-failed scenarios) coverage will tell

## P2 Medium:

_Can be done by someone else once P1s are finished._

- [ ] Refactor?
- [ ] merge npm-extended with regular npm build (different dependencies)
- [ ] add builds to npm (to avoid yarn:build connect)
- [ ] npm lib build and push from CI
- [ ] Permissions in manifest
- [ ] Auto-generated docs
- [ ] React front-end
- [ ] I18n support
- [ ] integration tests: web with popup mode (puppetier?), webextensions (background and front scripts)

## P3 Low:

_Can be done by someone else once P1s are finished._

- [ ] connect landing page (connect explorer) + stored permissions management (list what was allowed by domain)
- [ ] auto-generated method params + runtime validations based on some json(?) scheme
- [ ] unify methods and method params (for example: `getAddress` should be an abstract and decide whenever use `bitcoinGetAddress` or `ethereumGetAddress`)
- [ ] trezor-suite intents instead of popup (if some 3rd party app wants to use Trezor it should open suite-desktop app if installed)
- [ ] split UI logic into 2 parts: iframe above 3rd party apps (pairing/webusb support, infos, warnings etc) + popup in new window (sensitive actions like permissions/pin/passphrase)
- [ ] method chaining (example: call getPublicKey, getAddress ... in a single session)

**Comment by tsusanka** [comment]
My prioritisation draft:

## P1 High:
- [ ] Move to monorepo. create multiple packages: 
    - [ ] core (nodejs essential)
    - [ ] UI (popup, may be used in suite-desktop as well?),
    - [ ] UI (landingpage/connect-explorer),
    - [ ] web wrapper(3rd party popup usage),
    - [ ] webextension-background/electron-layer wrapper
- [ ] TypeScript support
- [ ] Refactor
- [ ] more unit tests (btc-like: ltc, and others supported, errors, invalid-failed scenarios) coverage will tell

## P2 Medium:
- [ ] merge npm-extended with regular npm build (different dependencies)
- [ ] add builds to npm (to avoid yarn:build connect)
- [ ] npm lib build and push from CI
- [ ] Permissions in manifest
- [ ] Auto-generated docs
- [ ] React front-end
- [ ] I18n support
- [ ] integration tests: web with popup mode (puppetier?), webextensions (background and front scripts)

## P3 Low:
- [ ] connect landing page (connect explorer) + stored permissions management (list what was allowed by domain)
- [ ] auto-generated method params + runtime validations based on some json(?) scheme
- [ ] unify methods and method params (for example: `getAddress` should be an abstract and decide whenever use `bitcoinGetAddress` or `ethereumGetAddress`)
- [ ] trezor-suite intents instead of popup (if some 3rd party app wants to use Trezor it should open suite-desktop app if installed)
- [ ] split UI logic into 2 parts: iframe above 3rd party apps (pairing/webusb support, infos, warnings etc) + popup in new window (sensitive actions like permissions/pin/passphrase)
- [ ] method chaining (example: call getPublicKey, getAddress ... in a single session)

**Comment by tsusanka** [comment]
We have agreed with @szymonlesisz the first step is to make a `connect-common` / `connect-data` package that will contain static files (protobuf etc.) taken from trezor-common. Connect will start using this package until the point we move it itself to the monorepo, very similarly to `rollout`.

@szymonlesisz we have also discussed github.com/trezor/trezor-common with @matejcik and we want to keep it, we do not know how many 3rd parties use it. So let's not optimise this prematurally and simply add it as a git submodule for the whole monorepo.

**Comment by tsusanka** [comment]
Let's do https://github.com/trezor/trezor-suite/issues/4363 as the first step.

**Comment by mroz22** [comment]
The "refactor" part was not fully done. But connet is in the monorepo at last.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
