### ISSUE TITLE
[Epic]  Tests

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#421]
Parent of

- [x] #420 Write more test for reducers
- [x] #419 Write more test for actions
- [ ] #317 Performance testing
- [x] #253 Write more test cases for utils
- [ ] more cypress tests
- [x] integration tests againts bridge and emulator #825

**Comment by mroz22** [comment]
Note to my future self or anybody handling problem with tests duration:
https://github.com/kensho/multi-cypress
