### ISSUE TITLE
[Epic] Backup device

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#451]
There should be: 
- [x] notification in suite when backup is not done (#448)
- [x] page with backup (#448)
- [ ] working backup in onboarding (probably works, does not have tests yet)

Backup should work 
- [x] for T1 basic (#457)
- [ ] for T1 some visual progress? (needs UX)
- [x] for T2 basic (#457)
- [ ] for T2 shamir somehow different? (needs UX)
- [ ] backup should not interfere with other calls to device. currently it does not work when there is discovery process in progress
- [ ] It should have decent test coverage
- [ ] It should be organized in `deviceManagement` section 
- [ ] There should probably be big red notification when device has failed backup
