### ISSUE TITLE
Further Linux integrations [epic]

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#4518]
1. Install handlers (these should be possible via already deployed AppImage, but will apply for other methods below):

- [x] udev rules - https://github.com/trezor/trezor-suite/issues/3664
- [ ] desktop file
- [ ] URI handler (this is probably done via desktop file)

2. Enable new Linux build targets:
- [ ] DEB (signed with GPG)
- [ ] RPM (signed with GPG)

3. Create repositories:
- [ ] for DEBs from step 2 via `createrepo` (see below)
- [ ] for RPMs from step 2 via `dpkg-scanpackages` (see below)
- [ ] Snap https://github.com/trezor/trezor-suite/issues/3696
- [x] Flatpak https://github.com/trezor/trezor-suite/issues/3697

---

* `createrepo`/`dpkg-scanpackages` guide: https://www.percona.com/blog/2020/01/02/how-to-create-your-own-repositories-for-packages/

**Comment by jerechinsky** [comment]
Moving this to product column for product team to decide the priority of these Linux integrations.

**Comment by melroy89** [comment]
I'm a linux user so 👍🏽 from me!
