### ISSUE TITLE
[Epic] Device settings

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#456]
Function parity with mytrezor: 

- [x] Add device settigns page
- [x] Change label
- [x] Change PIN
- [x] Turn on/off passhphrase
- [x] Change homescreen from predefined images
- [ ] Change homescreen from custom image upload
- [x] Screen rotation
- [x] Wipe device
- [ ] Handle result of each operation. Probably notification? 
- [ ] Consider basic options / advanced (like in mytrezor).

**Comment by mroz22** [comment]
closing, there are newer issues targeting this
