### ISSUE TITLE
[TRACKER] @trezor/transport followup

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#4601]
- [x] archive https://github.com/trezor/trezor-link
- [x] update index redme
- [x] release @trezor/transport to npm (under @trezor org)
- [ ] add logging back (sorry, forgot about it) [original decorator](https://github.com/trezor/trezor-link/blob/9c200cc5608976cff0542484525e98c753ba1888/src/debug-decorator.js), [implementations 1](https://github.com/trezor/trezor-link/blob/9c200cc5608976cff0542484525e98c753ba1888/src/bridge/v2.js#L56), [implementations 2](https://github.com/trezor/trezor-link/blob/9c200cc5608976cff0542484525e98c753ba1888/src/lowlevel/webusb.js#L49) +withSharedConentions 
- [x] implement @trezor/transport as dependency into connect
- [x] resolve exceptions in eslint config in @trezor/transport package. these are going to require some refactoring of transport layer
- [x] finish transport e2e tests that were separated into this branch https://github.com/trezor/trezor-suite/tree/transport-e2e
- [x] #5068 
- [x] #5069 

consider (ideas from #2923): 
 - ~~use .proto files~~ probably doesnt make sense, but we may revisit it later
 - ~~allow multiple protobuf sets/instances~~ this is imho antipattern
 - http requests cancelation
 - general cancel logic (currently handled by connect)
 - enumeration cycle module (currently handled by connect) #5035
 - http requests race conditions (currently handled by connect)

-----

consider https://github.com/trezor/trezor-suite/issues/1642 (discuss with matejcik)

____ 

tansferred from https://github.com/trezor/trezor-link/issues/40

problems:

- incremental device path is missing (there could be two unreadable devices)
- error handling needs to be implemented differently on user side (example in connect)

solution:
- process hid devices is the same way as bootloader devices
- master/src/lowlevel/webusb.js#L86

process unreadableHidDeviceChange internally and resolve it by enumerate response

___

transferred from https://github.com/trezor/trezor-link/issues/4

We need to export error messages up, to avoid string comparison.
Example:

trezor-link will throw Error("device not found"); to catch it and react properly i need to compare error.message with local string "device not found".

Better solution is:

```
export const DEVICE_NOT_FOUND = new Error('device not found');

```
then:

```
import { DEVICE_NOT_FOUND } from 'trezor-link';
```
and then:
```
if (error === DEVICE_NOT_FOUND) { ... }
```
