### ISSUE TITLE
Data analytics: onboarding tracking

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#4730]
Currently we do not tracking all useful information from onboarding proccess (c_type: 'initial-run-completed').

To be added:

- [x] skip firmware update
- [x] skip PIN
- [x] skip backup
- [x] Onboarding lenght: track the duration of the entire process
- [x] When Create seed: track Seed type
- [x] When T1 Recovery: track recovery type

**Comment by STew790** [comment]
**QA OK**

Data are correctly tracked in onboarding process:

![image](https://user-images.githubusercontent.com/48477147/156574346-ea8a3d43-2f98-41e5-bd4d-5ec7a4191b7e.png)
![image](https://user-images.githubusercontent.com/48477147/156574385-0dc943af-c564-4e32-9771-0663c7102bb5.png)
![image](https://user-images.githubusercontent.com/48477147/156574413-e919ed47-9a34-4bb1-84f8-73ebc6536f0d.png)

**Info:**
 - Suite version: web 22.3.0 (c63e333d70360823f462bfb21f2b6d52ec09444f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.3 regular
