### ISSUE TITLE
Implement Submarine Swaps (POC)

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4800]
Proof of Concept, which allows the user to recharge the LN wallet or pay LN invoices directly from the Trezor. 
_We do not address the opposite direction at this stage._

**Idea:**
User paste his invoice into send form. (Must include the amount requested)
Suite extends send form and add more information about swap.

**Subtasks from user perspective:**
- [x] Identify LN address
- [x] Read amount from the invoice
- [x] Inform user about:
    1. how much he gets (invoiced amount)
    2. that transaction might fail - he will receive money back to new address of a same account
    3. receivers on-chain address
    4. service fee
- [x] Fill in calculated amount (amount from invoice + service fee)
- [x] Inform user about process - pending transaction,..  *maybe option to request refund if something fails?*

---
- [ ] Figure out where to store transaction info

[https://submarine.corp.sldev.cz/](https://submarine.corp.sldev.cz/)

**Comment by hynek-jina** [comment]
It's dependent on: https://github.com/trezor/trezor-firmware/issues/1430

**Comment by prusnak** [comment]
> It's dependent on: [trezor/trezor-firmware#1430](https://github.com/trezor/trezor-firmware/issues/1430)

It's not dependent on this anymore. We have changed the mechanism from Payment Request to using a new Output Type.

Now it is dependent on https://github.com/trezor/trezor-firmware/pull/2136

**Comment by hynek-jina** [comment]
**POC was performed successfully**
There wasn’t discovered any blocker from technical perspective.
Open questions for further development are documented here: [trezor-suite/README.md at feat/submarine-swaps-poc · trezor/trezor-suite · GitHub](https://github.com/trezor/trezor-suite/blob/feat/submarine-swaps-poc/packages/lightning/README.md)

## Next steps
- Assign responsible product owner and set the priority
- Write product specification
- FW support [trezor/trezor-firmware#2136](https://github.com/trezor/trezor-firmware/pull/2136)
