### ISSUE TITLE
CI / tests tracking issue

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#4866]
- [ ] github actions OS runners matrix (osx + windows)
- [ ] collect coverage (jest, karma) from separated CI jobs
- [ ] ~~karma: add firefox workspace~~ done using playwright
- [x] karma: implement in gitlab
- [ ] ~~karma: handle new window opened (popup mode)~~ done in playwright
- [ ] ~~karma: move jasmine matcher (toMatchObject, expect.any in getFeatures fixtures) to karma plugin~~ karma deprecated, moving to playwright
- [ ] ~~karma: serve from https (webusb case)~~ karma depracted testing these things using playwright on sldev
- [ ] ~~karma: add more browser/popup behavior scenarios~~ there is a popup test using playwright
- [ ] ~~karma: add webextension scenarios~~ there is a basic test using playwright
- [ ] ~~karma: add webusb scenarios (mock?)~~ not really possible
- [ ] missing fixtures trezor/trezor-suite#4867
- [ ] unit tests for method params, WIP PR: https://github.com/trezor/connect/pull/782 depends on https://github.com/trezor/trezor-suite/issues/5297
- [ ] unify tests with https://github.com/trezor/trezor-firmware/tree/master/common/tests/fixtures/cardano
- [x] move tx cache to `trezor-common`
- [x] move fixtures to `trezor-common`
- [x] refactor all `signTransaction` tests to refTx from cache OR mock blockbook to return from cache (or both?)
- [x] remove legacy tests `src/__tests__`

**Comment by tsusanka** [comment]
@mroz22 @szymonlesisz I think more things are done already? Could you update the check boxes?

**Comment by szymonlesisz** [comment]
i think nothing was changed in that area

**Comment by mroz22** [comment]
checkboxes updated.

**Comment by mroz22** [comment]
> - [ ] collect coverage (jest, karma) from separated CI jobs

this worked for me to merge reports https://stackoverflow.com/questions/62560224/jest-how-to-merge-coverage-reports-from-different-jest-test-runs#answer-63008134
