### ISSUE TITLE
Connect & Tor tracking issue

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#4894]
- [ ] detect .onion origin in web env and set `setting.useOnionLinks` to true
- [x] BLOCKCHAIN.CONNECT should return { url: 'btc1.trezor.op`, onionUrl?: 'btc1.xxx.onion` }
- [x] accept proxyAgent options in `setProxy` method

**Comment by martykan** [comment]
Probably not relevant anymore right? Tor urls are handled by `@trezor/urls` package
