### ISSUE TITLE
connect-popup bugs tracker

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#4962]
Connect popup sometimes closes before it renders "permissions scree".

It might also be connected with some of these: 
- [x] https://github.com/trezor/trezor-suite/issues/4877
- [x] https://github.com/trezor/trezor-suite/issues/4883
- [x] https://github.com/trezor/trezor-suite/issues/4888
- [x] https://github.com/trezor/trezor-suite/issues/4857
- [ ] [Metamask + Trezor pop up window automatically closes without signing](https://github.com/trezor/connect/issues/784#top)

**Comment by nopty** [comment]
Any updates?

**Comment by Hannsek** [comment]
@nopty All of the issues should be fixed by now.
