### ISSUE TITLE
Modal-specific guide anchors

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#5062]
Implement a guide button in the [user context modal](https://github.com/trezor/trezor-suite/blob/8316e3bb4893569d4c25c93057bc5afd9a198899/packages/suite/src/components/suite/modals/index.tsx#L151) headers, which leads to a specific guide page related to the content of the modal, as seen [here](https://www.figma.com/file/5FkvrkgeBliiSbV3AbsTey/Exploring-Guide?node-id=730%3A6567)

<img width="300" alt="image" src="https://user-images.githubusercontent.com/45338719/157061546-11cd7b29-f14f-46bc-9ece-9fc735ea56a3.png">

**Task flow:**

- [ ] Create a list of modals and related actions
- [ ] Check if there are guide pages related to those actions
- [ ] Add missing guide pages
- [ ] Wait for @marekrjpolak's modal refactor to end **(🛑 blocker)**
- [ ] Implement the anchors

**Comment by hynek-jina** [comment]
Suite Guide will be reworked.. so please wait for more inputs from @ElKaDu before implementing.
