### ISSUE TITLE
create desktopApi.handshake flow

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5627]
Extends https://github.com/trezor/trezor-suite/issues/4809

Desired app workflow:
1. create BrowserWindow (src-electron/app.ts init function) and start **only** hang-detect module, nothing else
2. renderer is loaded, call desktopApi.handshake [1]* and wait for the response (suite-desktop/src/index window.onload) consider rendering only lightweight preloader component without whole redux stack while waiting
3. handle handshake invocation (src-electron/app.ts)
   - clear timeout in hang-detect module
   - get system data (move this part from src-electron/app.ts init function)
   - loadModules (move this part from src-electron/app.ts init function) [2]*
   - respond with success or error
4. handle response in renderer, call store.dispatch action [3]* with data from handshake, handle action in reducer(s) **or** display error
5. render the whole thing (Main component)

---

[1] in the future we can preload indexedDB before the handshake and use stored data as a parameter of handshake method (like pass stored tor or autoupdate settings) #5534 this way we can get rid of "parallel storage", source of truth will be only in indexedDB (tor url, port, enabled etc)
[2] - it may be even faster/better if we split handshake into two steps: handshake1 - get only system data (to get "theme" as fast as we can to prevent "blink"), handshake2 - call `loadModules` (start tor, bridge etc)
[3] - in the future instead of dispatching action we can extend preloaded data from indexedDB and use them as initialState in `store` creation #5534

---

Problems/steps:
- [ ] we want to know some information about the system paths, theme etc before first render. related to https://github.com/trezor/trezor-suite/issues/4809 and  https://github.com/trezor/trezor-suite/pull/5534
- [ ] electron main process is starting up own subprocesses (tor, bridge etc) before it even knows that the app (renderer) is loaded properly. may be related to https://github.com/trezor/trezor-suite/issues/5612
- [ ] use data from the handshake (resourcePath) to get rid of [this workaround](https://github.com/trezor/trezor-suite/blob/develop/packages/suite-desktop/src-electron/modules/trezor-connect-ipc.ts#L72-L76=), set `basePath` in `TrezorConnect.firmwareUpdate` call (firmwareActions) instead
- [ ] get rid of `desktopApi.getUserDataInfo` function and module  (data should be present in handshake response > reducer, same case as firmwareUpdate)
- [ ] get rid of `desktopApi.clientReady` function (functionality replaced by handshake)

---
Probably follow up:
- [ ] finish state preloading #5534
- [ ] refactor auto-updater module and related events (info about the update may be sent in handshake response)
- [ ] find and refactor all others `desktopApi` calls from `useEffect` across suite components (tor/status, autoupdate, etc)

---
### QA ###
Please read [What to test](https://github.com/trezor/trezor-suite/pull/5632#user-content-qa) section in PR :heart:

**Comment by matejkriz** [comment]
@trezor/qa Please pay attention to "bridge is not running" error during startup of the app. We're not entirely sure it's a bug, but more of us have seen it.

**Comment by bosomt** [comment]
@matejkriz do you have any more information about that `bridge is not running` problem ?
- is it reported in log or in app ?
- is it platform specific ?
- i was not able to reproduce it for days on my macARM
