### ISSUE TITLE
Enable to import more coins assets

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6686]
Firstly, we'll need to enable more coins to be scanned and imported into the mobile app. We have a list of networks that are supported in the desktop version and we should keep it same.

- [x] [EnableCoins: Update available coins and selecting one#6958](https://github.com/trezor/trezor-suite/issues/6958)
- [x] [Allow import through scan as well as typed adress through onboarding](https://github.com/trezor/trezor-suite/issues/6960)

- [x] #6988

There will be some problems. Mainly, there is currently no validation so we need to have a way to stop user from importing xpub of BTC that can look like Dogecoin in the app. This is still unclear how we will implement it.
- [ ] [Validate xpub in onboarding flow](https://github.com/trezor/trezor-suite/issues/6683)

Also, we need to be able to fetch fiat rates for these coins to be able to display real portfolio data in the graph. This is a problem because some of the coins don't have fiat rates available in blockbook, so we will need to fetch them elsewhere if that's the case. Needs some more looking into.
- [ ] [EnableCoins: Use other imported accounts for graph](https://github.com/trezor/trezor-suite/issues/6971)

**Comment by juriczech** [comment]
Is there a design for this? Currently in onboarding, import of xpubs is very much dependent on the currency you select in switch (bitcoin / testnet) and for this, there will need to be predefined coin before sending xpub to connect.

**Comment by mnuky** [comment]
yep, still under the construction with design. I will change the status to Product until we have the design.
