### ISSUE TITLE
Coinjoin followup tracking

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#6698]
Tracking list for followups:
- [x] Restore coinjoin session: `coinjoinAccountActions.restoreCoinjoinSession`
  > decision should Trezor ask for confirmation if it's already preauthorized but maxRounds racalculation changed? should it updated in suite CoinjoinSession? possible desyncronization: Trezor has authorized 10 but suite realculated this to 11, then will try to attend this 11 round, got to a signing phase receive error on signing (max round exceeded) and breaks round for everyone 

- [x] Catch known network errors in `@trezor/coinjoin/utils/http` like `ECONNRESET` network timeout (tor circuit error) and optionally retry N times or retry until optional deadline
  > one network error should not break the whole process,
  > implemented in #6745 and #7133 and #7209 and #8661
  
- [ ] extend `coordinatorRequest` to return used params if request fails. coordinator allows to repeat the requests if same params were used. see current implementation in connectionConfirmation #7209

- [x] Catch known errors from coordinator in `@trezor/coinjoin` round phase process and react to them accordingly
  https://github.com/trezor/trezor-suite/commit/8cc706cf1d9e35c352aacb84823542326441a1c8

- [x] Store `CoinjoinPrison` in suite storage (if device remembered) and use it in `CoinjoinClient` initialization while restoring coinjoin session/creation new one #8549

- [ ] Store input `registrationData` and `confirmationData` in suite storage (if device remembered) and use it in `CoinjoinClient` initialization while restoring coinjoin session/creation new one
  > There still might be a chance to fully restore the session after reload/disconnection/unregister etc

- [ ] Review followups
  > use objects instead of arguments https://github.com/trezor/trezor-suite/pull/6712#discussion_r1009648999

- [ ] Handle and display coinjoin backend disconnection
  > followup of https://github.com/trezor/trezor-suite/pull/6848

- [x] implement blaming rounds https://github.com/trezor/trezor-suite/pull/7246

- [x] optimize account discovery (issue https://github.com/trezor/trezor-suite/issues/7390)
  > discovery of [vpub5Yme8...Q3CTZM9](https://tbtc1.trezor.io/xpub/vpub5Yme8cvVDuECgS5vuY8rYyVMrnSvDaUwbDeKLNhh3BKZYe3fpKKapVQUFAEVpyBbwaUhZLeZLcwcoRMweSfRtFxB6MenWh3NweXrQ3CTZM9) (~600k blocks, ~540 txs) over Tor now takes approx. 43 minutes
  > - filters could be fetched faster, independently on blocks/transactions
  > - remove the need of fetching txs by two requests (block + every relevant tx in it)
  > - fetch all mempool txs with one request (from coordinator, not blockbook)
  > - store fetched filters for later usage (e.g. discovering another account)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
