### ISSUE TITLE
Core discovery logic to common (redux)

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6884]
```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/8861
- [ ] https://github.com/trezor/trezor-suite/issues/8914
- [ ] https://github.com/trezor/trezor-suite/issues/9004
- [ ] https://github.com/trezor/trezor-suite/issues/9172
- [ ] Implement reducer in `suite-native`
```
