### ISSUE TITLE
Core firmware logic (redux)

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6885]
At least some part of it like FW verification (we don't need install/update), but maybe it will easier to just migrate it
```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/8862
- [ ] https://github.com/trezor/trezor-suite/issues/9145
- [ ] Move to common
```
