### ISSUE TITLE
[EPIC] Display of ETH tokens

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7068]
## Initial supported tokens
|Token|Contract|
|-|-|
|USDT|0xdac17f958d2ee523a2206206994597c13d831ec7|
|USDC|0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48|
|DAI|0x6b175474e89094c44da98b954eedeac495271d0f|
|SHIB|0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce|
|UNI|0x1f9840a85d5af5bf1d1762f925bdaddc4201f984|
|LEO|0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3|
|WBTC|0x2260fac5e5542a773aa44fbcfedf7c193bc2c599|
|LINK|0x514910771af9ca656af840dff83e8264ecf986ca|
|OKB|0x75231f58b43240c9718dd58b4967c5114342a86c|
|CRO|0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b|
Connected to Desktop Suite issue: https://github.com/trezor/trezor-suite/issues/7298

**Description of behaviour**
**1. Import new token**
- User can select to import top 10 ERC20 tokens - tokens are displayed in the list with tag "Run by ETH"
- When user selects ERC20 Token (eg. Shiba Inu) we display toaster with notification that this is ERC 20 token and it is related to ETH
- User then see opened Hint page where to find ETH receive address in order to scan the QR code and import the token
- User scans the Receive address - we display number of assets we found (but only ETH + end all tokens with FIAT value), we ignore all other tokens
- User can delete those he does not want to see in the app
- When user clicks on confirm he is redirected to Dashboard
- modal with information that this is ETH token is displayed every time user imports ETH token

**2. Dashboard**
- User sees ERC20 tokens as separated tiles in the list of coins with their value

**3. List of assets page**
-  ER20 Tokens are displayed as separated units but underneath the ETH they belong

**4. Receive flow**
- When user would like to create receive request for ERC20 Token, he can go via menu / asset detail as with normal coins
- the only differences is that there is message for users on Receive page, that this is ERC20 token and Receiving address is actually ETH Address

**5. Delete ERC20 token**
- When user goes token detail asset, he can delete the asset
- Deleting the asset  should not affect other ERC20 tokens and ETH

**6. Delete ETH when there are ERC20 Tokens imported**
- When user wants to delete imported ETH asset and there are some ERC20 Tokens underneath, we tell user that if he deletes ETH, all related tokens will be deleted, too

**7. ETH Asset detail**
- When there are related ERC20 tokens to ETH asset we display option in transaction list to display just ETH transactions or all transaction incl. ERC20 Tokens

WIP Figma screens: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14956%3A61406&t=DanJhjDpokLX7ICG-1

```[tasklist]
- [ ] https://github.com/trezor/trezor-suite/issues/7643
- [ ] https://github.com/trezor/trezor-suite/issues/7644
- [ ] https://github.com/trezor/trezor-suite/issues/7645
- [ ] https://github.com/trezor/trezor-suite/issues/7647
- [ ] ERC20 n.6 - Select which accounts could be imported (could be merged with #7595)
- [ ] https://github.com/trezor/trezor-suite/issues/7595
- [ ] https://github.com/trezor/trezor-suite/issues/7881
### Tasks

**Comment by rulbricht** [comment]
In addition to this, the ERC20 tokens should support the same EXPORT function into csv/pdf/json
