### ISSUE TITLE
Analytics for mobile app

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7141]
```[tasklist]
- [ ] https://github.com/trezor/trezor-suite/issues/7596
- [ ] https://github.com/trezor/trezor-suite/issues/7083
- [ ] https://github.com/trezor/trezor-suite/issues/7597
- [ ] https://github.com/trezor/trezor-suite/issues/7710
### Tasks
```
