### ISSUE TITLE
Create Storybook 2.0

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#739]
**Create Storybook 2.0 based on UI/UX from Product** 

https://app.zeplin.io/styleguide/5dadac23b86447128579b03c

A good example of storybook https://storybook.grommet.io/

- [x] https://github.com/trezor/trezor-suite/issues/767 Setup components + storybook 2.0
- [x] Buttons #781
- [x] Typography (Heading, Paragraph, Link) #802 
- [x] Notifications #804 
- [x] Icons #798
- [x] Input Text #795
- [x] Textarea #809
- [x] Select #872 
- [x] Checkbox & Switch #877 
- [x] Coins & Trezor logos #884 
- [x] Modals #889 
- [x] Loaders #963
- [ ] Tooltip #988 
- [ ] Button Pin
- [ ] Input pin

- [ ] Images
- [x] Variables
- [x] Colors
- [x] Anchors
- [x] Fonts

- [ ] Typescript
- [ ] Snapshot tests
- [ ] Storybook style (add trezor logo and colors ...)

**Comment by ZdenekSL** [comment]
@vladimirvolek Please schedule a meeting and decide how this should be done.
@keip Please, create sub-tasks for this Epic
