### ISSUE TITLE
[Epic] React Native

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#740]
- [x] typecheck
- [ ] storage https://github.com/trezor/trezor-suite/issues/765
- [ ] components
- [ ] react hooks
- [x] upgrade to the latest version #760 #764 #775 
- [x] build android #772
- [ ] build ios  
- [x] build android in CI #760 
- [ ] write java adapter for usb communication
