### ISSUE TITLE
Dashboard [EPIC]

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#831]
Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5def869efffd4216938e514e
- [x] Empty State https://github.com/trezor/trezor-suite/issues/832
- [x] Graph https://github.com/trezor/trezor-suite/issues/833
- [x] Assets https://github.com/trezor/trezor-suite/issues/837
- [x] Connection Status https://github.com/trezor/trezor-suite/issues/834
- [x] Security Levels https://github.com/trezor/trezor-suite/issues/835
- [x] News https://github.com/trezor/trezor-suite/issues/836
