### ISSUE TITLE
Settings [EPIC]

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#844]
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f7ad36cb91f2de63ec5

- [x] General https://github.com/trezor/trezor-suite/issues/845
- [x] Device https://github.com/trezor/trezor-suite/issues/846
- [x] ~~Dashboard https://github.com/trezor/trezor-suite/issues/847~~
- [x] ~~Wallet https://github.com/trezor/trezor-suite/issues/848~~
- [x] Coins https://github.com/trezor/trezor-suite/issues/849
