### ISSUE TITLE
[EPIC] Discreet mode improvements

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8497]
As a user I would like to enable discreet mode by tapping on portfolio balance in order to hide the balances faster.

Plus we have to discuss the UI of blurred balances, it does not look nice, either we make it nicer or replace by stars or something else. 

Acceptance criteria:
When user switch on the discreet mode in the Settings for the first time, we show the bottom sheet with information that he can do it directly from dashboard by tapping on balance amount
If user taps on portfolio balance amount for the first time, we will display bottom sheet with information that this action triggers discreet mode
When user taps on the portfolio balance, the amounts are hidden

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/58Gop0xL5XvNnCZjP7esq9/%5Bs2.0%5D-Mobile?type=design&node-id=18104%3A115299&t=WREkjCZb2ImnqtEf-1
```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/8679
- [ ] https://github.com/trezor/trezor-suite/issues/8680
- [ ] https://github.com/trezor/trezor-suite/issues/8079
```
