### ISSUE TITLE
Labelling [EPIC]

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#855]
Add label in Receive tab: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1cc52ec4d697545ede13
Connect to Dropbox in settings:
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f7ad36cb91f2de63ec5

**Comment by ZdenekSL** [comment]
What I think we will need:
- [ ] Dropbox flow and screens
- [ ] Where the "add label" will be visible
- [ ] edit/delete?
- [ ] export?

**Comment by mroz22** [comment]
- [ ] trezor-connect implementation

**Comment by glacierbits** [comment]
Outdated. New issue coming.
