### ISSUE TITLE
Deprecate very old firmwares

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8778]
We can mark firmware upgrade for specific version as required and it means that user is forced to update in order to use Suite.

Let's discuss the priority and plan.
```[tasklist]
### Tasks
- [ ] Document testing FW update/initialization in Suite using T1 devkit
- [ ] Put together an overview of issues related to FW update/initialization
- [ ] Decide what needs to be fixed before deprecation
- [ ] Prepare a communication plan
```

**Comment by tsusanka** [comment]
Related: https://github.com/trezor/trezor-suite/issues/3728

**Comment by matejkriz** [comment]
> Related: #3728

that's the one I tried looking for and didn't find - it's more duplicate than just related, let's close this one and keep discussion in the original one
