### ISSUE TITLE
test: connect-popup with webextension

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#8883]
We already have some webextension tests. Lets cover also all the edgecases for trezor-connect implementation in webextensions. It should be possible to achieve this by wrapping connect-explorer into a webextension and running all the connect-popup tests we already have for connect-popup web version against the same but webextension version. 

Do you think it will be possible? @karliatto 
```[tasklist]
### Tasks
- [x] Create a web extension with connect explorer
- [x] Build webextension with Connect explorer in CI
- [x] Make current popup tests for connect-explorer work with connect-explorer-webextension
- [ ] Allow building connect-explorer-webextension with old NPM packages
```

**Comment by karliatto** [comment]
I am closing this issue, most of the tasks are completed and the remaining task "Allow building connect-explorer-webextension with old NPM packages" will be address as a follow-up of Connect Popup tests migration to GitHub Actions in https://github.com/trezor/trezor-suite/issues/7916
