### ISSUE TITLE
Secure desktop app [EPIC]

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#901]
1. Implement connection whitelist in electron wrapper
2. Follow the instructions here: https://github.com/electron/electron/blob/master/docs/tutorial/security.md

Child tasks
- [x] #916 Only load secure content
- [x] #917 Disable the Node.js integration in all renderers that display remote content
- [x] #918 Enable context isolation in all renderers that display remote content
- [x] #919 Use ses.setPermissionRequestHandler() in all sessions that load remote content
- [x] #920 Do not disable webSecurity
- [x] #921 Define a Content-Security-Policy and use restrictive rules (i.e. script-src 'self')
- [x] #922 Do not set allowRunningInsecureContent to true
- [x] #923 Do not enable experimental features
- [x] #924  Do not use enableBlinkFeatures
- [x] #925 Webview: Do not use allowpopups
- [x] #926 Webview: Verify options and params
- [x] #927 Disable or limit navigation
- [x] #929  Do not use openExternal with untrusted content
- [x] #928 Disable or limit creation of new windows
- [x] #930 Disable the remote module
- [x] #931 Filter the remote module
- [x] #932 Use a current version of Electron

**Comment by keraf** [comment]
Some points in the list are not applicable to our application but all that are have been addressed in PR #2275. 

The OAuth flow has not been given much attention as it is going to be rewritten (see #2304).

**Comment by bosomt** [comment]
can we get more info how can we test this issue ?
does it need QA ?

**Comment by prusnak** [comment]
@keraf Do you have some scenarios in mind that QA can test now? Or will we test this as part of regular desktop app testing?

**Comment by keraf** [comment]
Can't really think of any test scenarios, this is mostly to prevent unexpected behaviors that could compromise the user's security. I guess this will be best checked during a security review.

**Comment by prusnak** [comment]
OK, thanks. Moved to "Approved"
