### ISSUE TITLE
[EPIC] Connect Trezor Device and unlock it

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9181]
As a user I would like to be able to connect my Trezor Device and be able to unlock it in order to access my funds. 

**Highlevel acceptance criteria:**
User can connect device (we can identify connected Trezor One device, all other devices are not recognised until device is unlocked)
If the device is protected by PIN, user can insert PIN either on device or on mobile screen based on device type

Detailed acceptance criteria:
- When user connects TT / TS3 and the device is protected by PIN, user inserts the PIN on the device
- When user connects device which is not protected by PIN, we redirect to "Loading screen"
- When user connects T1 he is redirected to "key pad" screen and inserting the PIN on mobile screen keypad
- When user unclocks the device, he is redirected to "Loading screen" 
- It does not matter from which screen user connects the device, it always goes to "Loading screen" once the device is unlocked

https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=2324-249&mode=design

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/9418
- [ ] https://github.com/trezor/trezor-suite/issues/9453
- [ ] https://github.com/trezor/trezor-suite/issues/9454
- [ ] https://github.com/trezor/trezor-suite/issues/9682
- [ ] https://github.com/trezor/trezor-suite/issues/9509
- [ ] https://github.com/trezor/trezor-suite/issues/9603
- [ ] https://github.com/trezor/trezor-suite/issues/6886
- [ ] https://github.com/trezor/trezor-suite/issues/9452
- [ ] https://github.com/trezor/trezor-suite/issues/9834
- [ ] https://github.com/trezor/trezor-suite/issues/9836
```

**Comment by Hannsek** [comment]
> User can connect device and we identify it
fyi, We can currently identify only model 1 when it is locked. Not the TT/T2B1 (core).

It has some pros and cons. If we would like to identify core even if it is locked, there is significant work to do on fw side. We would have to have strong use cases for that…

**Comment by juriczech** [comment]
For this, we will need a design for what should happen when I'm browsing the dashboard of synced assets and connect trezor. We need some kind of modal that will just pop up with an option to handle that device connection.

**Comment by STew790** [comment]
**QA OK**

**Info:**

Mobile Suite Version: 23.11.1(602)
OS: Android 12
