### ISSUE TITLE
[EPIC] Coin discovery and overview of my coins

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9183]
As a user I would like to see all my funds which are related to my standard wallet in order to get overview of my balance

**Highlevel acceptance criteria:**
When user connect and unlock the device, automatic discovery of all coins starts 
User can see all his funds on dashboard - we don't wait until all coins are loaded, we load them on the go
User can use the app before all the funds are loaded

**Detailed Acceptance criteria:**
- When user connects and unlocks the trezor device, screen with Connecting (Loading screen) appears
- After 2.5s user is redirected to Dashboard and sees loading skeleton until first asset is loaded
- Coin discovery can load only accounts with at least one TX history
- All assets are loaded gradually
- If no assets are discovered, we display "empty status" and inform user, that there are no assets discovered on the device
- If user wants to discover testnet coin, he has to go to debug menu and enable them there
- Coin discovery does not discover "Coinjoin accounts"
- User can use the app once first asset is loaded

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/9462
- [ ] https://github.com/trezor/trezor-suite/issues/9463
- [ ] https://github.com/trezor/trezor-suite/issues/9464
- [ ] https://github.com/trezor/trezor-suite/issues/9467
- [ ] https://github.com/trezor/trezor-suite/issues/9501
- [ ] https://github.com/trezor/trezor-suite/issues/9591
- [ ] https://github.com/trezor/trezor-suite/issues/9645
- [ ] https://github.com/trezor/trezor-suite/issues/9646
- [ ] https://github.com/trezor/trezor-suite/issues/9658
- [ ] https://github.com/trezor/trezor-suite/issues/9727
- [ ] https://github.com/trezor/trezor-suite/issues/9760
```

**Comment by Hannsek** [comment]
This is the ideal state. Don't know about the computer power needed. 🤔

**Comment by juriczech** [comment]
Prerequisite: https://github.com/trezor/trezor-suite/issues/9181 - we need to have unlocked device to be able to run discovery.

**Comment by PeKne** [comment]
All subtasks are done, closing...

**Comment by bosomt** [comment]
**QA OK**

96712ed - [develop] - feat(suite-native): analytics for connected device (#10115)
