### ISSUE TITLE
[EPIC] Manage my Trezor device

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9184]
As a user I would like to see information about my connected Trezor in order to stay informed and calm that I know what is happening. 

**Highlevel acceptance criteria:**
User can see that the device is connected
User can eject the device
User can get device info
User can switch to portfolio tracker

**iOS navbar content:**
- Link to sync another coin
- Link to eshop
- Link to Knowledge base

Android navbar content:
- Connect device
- Switch to device
- Switch to portfolio tracker

**Device info:**
When user access Device info page, he can see:
1. Type of the device
2. Name of the device
3. Picture of the device
4. Version of the FW
5. Link to eShop
6. If the FW version is up to date, we display message that the device is up to data
7. If the device FW version is old, we display message that the device is not up to date
8. There is option to get instructions how to update FW

Figma switcher: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=3930%3A20297&mode=design&t=RFYN940OZgyr4u1N-1
Figma device info: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=3804%3A15764&mode=design&t=RFYN940OZgyr4u1N-1

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/9648
- [ ] https://github.com/trezor/trezor-suite/issues/9733
- [ ] https://github.com/trezor/trezor-suite/issues/9734
- [ ] https://github.com/trezor/trezor-suite/issues/9759
- [ ] https://github.com/trezor/trezor-suite/issues/9883
- [ ] https://github.com/trezor/trezor-suite/issues/9747
- [ ] https://github.com/trezor/trezor-suite/issues/9856
- [ ] https://github.com/trezor/trezor-suite/issues/9982
- [ ] Device settings
- [ ] https://github.com/trezor/trezor-suite/issues/9993
```

```[tasklist]
### Tasks
```

**Comment by Hannsek** [comment]
> User can eject the device

What is the reason behind this? Just psychological?

**Comment by juriczech** [comment]
@Hannsek AFAIK it's the same mechanism as suite desktop is using, so I'm guessing just compatibility across apps.

**Comment by bosomt** [comment]
**QA OK**

### iPhone 11 / iOS - 23.11.1 (384) develop version
     ✅  navbar present and contains `Sync another coin` + and link to KB and eshop 
    
### Android 13 and Nothing phone 1 - 23.11.1 (597) develop version 
    ✅ navbar conians:    Connect device    Switch to device    Switch to portfolio tracker
    ✅ dev info contains: device Type, picture, fw version, eshop link, FW version is up to date,FW version is old, instructions how to upgrade, info when device is not setup
    ❌ dev info missing: device name

**Comment by bosomt** [comment]
>
