### ISSUE TITLE
[EPIC] Receive flow with connected Trezor Device

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9186]
As a user I would like to generate receive verified address for my coin in order to make sure I share the right address because my Trezor device never lies. 

**Highlevel acceptance criteria:**
User can reveal address for existing coins and verify it with Trezor Device

Detailed acceptance criteria:
- User can trigger the Receive either from bottom nav or from asset detail
- If user click on receive on navigation bar, he must first choose the asset he would like to receive to
- User can choose only from existing (discovered) assets. Feature to create new account / coin will come later in epic: https://github.com/trezor/trezor-suite/issues/9654) 
- When user chooses the asset, he lands on screen when he sees the asset he would like to receive to and partially shown address
- If user clicks on Show address first we display information bottom sheet which explains user what he needs to do. Then information why he does verify the address
- User has option to hide this information for next time
- User then lands on screen with revealed address and is prompted to confirm the address on Trezor Device
- If address does not match there user can click on the button and bottom sheet with instructions appear
- User can also learn more about the need of verifying addresses via click on the link
- If user clicks on the element “Confirm on Trezor” - we display bottom sheet info what user should do
- If user confirm the address on Trezor Device, the QR code and address is displayed. User can share or copy the address. 

**Address chunking acceptance criteria**
There will different view of the address per device:
TS3 - address is displayed in chunks and has its own font (Pixel Operator Mono 8, Regular)
TT - address is displayed in chunks and has its own font (Roboto Mono, Medium)
T1 - address is displayed as string (no chunks) and has its own font (Pixel Operator 8, Bold)

Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=2303%3A9941&mode=design&t=KK5AYCikGNAanrLR-1

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/9775
- [ ] https://github.com/trezor/trezor-suite/issues/9776
- [ ] https://github.com/trezor/trezor-suite/issues/9777
- [ ] https://github.com/trezor/trezor-suite/issues/9778
- [ ] https://github.com/trezor/trezor-suite/issues/10024
```

**Comment by bosomt** [comment]
**QA OK**

### iPhone 11 / iOS - 23.11.1 (384) develop version
     ✅  receive address is chunked, no change
    
### Android 13 and Nothing phone 1 - 23.11.1 (597) develop version 
     ✅ User can trigger the Receive either from bottom nav or from asset detail
     ✅ If user click on receive on navigation bar, he must first choose the asset he would like to receive to
     ✅ User can choose only from existing (discovered) assets
     ✅ When user chooses the asset, he lands on screen when he sees the asset he would like to receive to and partially shown address
     ✅ If user clicks on Show address first we display information bottom sheet
     ✅ User has option to hide this information for next time
     ✅ User then lands on screen with revealed address and is prompted to confirm the address on Trezor Device
     ✅ If address does not match there user can click on the button and bottom sheet with instructions appear
     ✅ User can also learn more about the need of verifying addresses via click on the link
     ✅ If user clicks on the element “Confirm on Trezor” - we display bottom sheet info what user should do
     ✅  If user confirm the address on Trezor Device, the QR code and address is displayed. User can share or copy the address.

     ❌ app ignores when i cancel confirmation of receive address on device via x button
### Address chunking
    ✅  - S3 - address is chunked
    ❌  - TT - address is NOT chunked with 2.6.3 FW,  not sure if it needs new fw or not /i see that in FW it was already merged to amster months ago/
    ✅  - T1 - address is not chunked as expected

**Comment by Hannsek** [comment]
> app ignores when i cancel confirmation of receive address on device via x button

@bosomt you mean after you click `QUIT`?

> ❌  - TT - address is NOT chunked with 2.6.3 FW,  not sure if it needs new fw or not /i see that in FW it was already merged to amster months ago/

2.6.3 supports chunked addresses

**Comment by bosomt** [comment]
- yes you press `x` and then `QUIT`
- yes it supports, but not yet supported in Connect, soon™️
