### ISSUE TITLE
[EPIC] View only - Access Trezor balances without connected device

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9187]
As a user I would like to keep access to my wallet assets in order to be able to check my funds without connected Trezor Device

> View-only mode formerly known as Remember mode

###  Highlevel acceptance criteria

- When the wallet is set to View-only, user can see his funds without connected device
- When the wallet is set to View-only, user can reveal receive address without connected device but there is warning
- User can switch off the settings for remembering the wallet

###  Detailed acceptance criteria:

**Setting up View-only** 
- When user connects Trezor device he sees "promotional bottom sheet" explaining View-only
- User can enable View-only directly from the bottom sheet
- When user clicks on "Enable", the feature from the bottom sheet, success message appears
- When user clicks on "Skip", the feature is disabled and the bottom sheet does not occur again when user reconnects the device

**Managing View-only**
- User can enable / disable feature in settings, section View-only
- User sees all the devices which are disconnected and in View-only
- User sees current connected device
- When user disable feature for disconnected Trezor, it disappears from the page
- User can access info bottom sheet explaining the feature more in detail
- So far it's 1 device ~ 1 wallet, so the settings is applied to Device's Standard wallet. With Passphrase it will be possible set up per wallets.

**App in View-only and disconnected Trezor**
- When user access disconnected Trezor, it is marked as View-only
- When user wants to reveal the receive address, he is informed that Trezor is not connected and address can't be verified
- If user clicks on Continue without verifying, receive address is revealed
- User can't add new coin / account

**Design**
[Figma](https://www.figma.com/file/KvbZGG16li6BA90Xtpf0BP/Device-interaction?type=design&node-id=970-17548&mode=design&t=M3ntlJw3jRHwNpAp-11)

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/11851
- [ ] https://github.com/trezor/trezor-suite/issues/11852
- [ ] https://github.com/trezor/trezor-suite/issues/11853
- [ ] https://github.com/trezor/trezor-suite/issues/11886
- [ ] https://github.com/trezor/trezor-suite/issues/11887
- [ ] https://github.com/trezor/trezor-suite/issues/11892
- [ ] https://github.com/trezor/trezor-suite/issues/11890
- [ ] https://github.com/trezor/trezor-suite/issues/11889
- [ ] https://github.com/trezor/trezor-suite/issues/11947
- [ ] https://github.com/trezor/trezor-suite/issues/11977
- [ ] https://github.com/trezor/trezor-suite/issues/12013
```

**Comment by shenkys** [comment]
[Design ready](https://www.figma.com/file/KvbZGG16li6BA90Xtpf0BP/Device-interaction?type=design&node-id=970-17548&mode=design&t=M3ntlJw3jRHwNpAp-11)

**Comment by mnuky** [comment]
closing - we don't work with EPICs as issues. Whole content moved to Milestone: https://github.com/trezor/trezor-suite/milestone/56

**Comment by mnuky** [comment]
closing- we no longer work with issues as epic, we will use Milestone instead. Content was moved to: https://github.com/trezor/trezor-suite/milestone/56
