### ISSUE TITLE
1. Staking

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9252]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/9258
- [ ] https://github.com/trezor/trezor-suite/issues/9259
- [ ] https://github.com/trezor/trezor-suite/issues/9253
- [ ] https://github.com/trezor/trezor-suite/issues/9255
- [ ] https://github.com/trezor/trezor-suite/issues/9257
- [ ] https://github.com/trezor/trezor-suite/issues/11438
- [ ] https://github.com/trezor/trezor-suite/issues/9277
- [ ] https://github.com/trezor/trezor-suite/issues/9274
- [ ] https://github.com/trezor/trezor-suite/issues/9268
- [ ] https://github.com/trezor/trezor-suite/issues/9267
- [ ] https://github.com/trezor/trezor-suite/issues/9272
- [ ] https://github.com/trezor/trezor-suite/issues/11407
- [ ] https://github.com/trezor/trezor-suite/issues/11583
```
