### ISSUE TITLE
2. Unstaking

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9279]
### User Story

As a staker
I want to unstake my Ethereum
So that I can buy NTFs

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/11402
- [ ] https://github.com/trezor/trezor-suite/issues/11406
- [ ] #9278
- [ ] https://github.com/trezor/trezor-suite/issues/9280
- [ ] https://github.com/trezor/trezor-suite/issues/11586
```
