### ISSUE TITLE
4. Ethereum staking set dressing

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9286]
```[tasklist]
### Tasks
- [ ] #9285
- [ ] https://github.com/trezor/trezor-suite/issues/9287
- [ ] https://github.com/trezor/trezor-suite/issues/11256
- [x] Skaking set dressing: Message system config
- [x] Staking set dressing: Responsive UI
- [x] Staking set dressing: Staked balance on dashboard
- [x] Staking set dressing: Analytics
```
