### ISSUE TITLE
UI Design review - bugs

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9307]
Printscreens:
![Image](https://github.com/trezor/trezor-suite/assets/84183817/902d67c3-87e3-4521-ab85-410063069065)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/02aadf35-06e5-4453-9fe0-35d810e080db)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/df27db2a-9dea-4ffd-a1c3-854a15098c93)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/9b4ca84e-8449-4b88-b1f8-6c9e30412895)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/b7471009-7e2a-4123-a201-aa5dd7e4a8d5)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/7197b8de-b021-499e-bf63-f6712a0fdbae)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/b81ef20c-6250-4e4c-86fb-f4e2c396811f)

Broken Android Receive screen
![Image](https://github.com/trezor/trezor-suite/assets/84183817/a341ef57-76b2-4ead-a2f5-136e01e06fd9)

```[tasklist]
### Tasks
- [x] Welcome flow - primary button - check the size, it should be bigger
- [ ] Text input - background has wrong colour and spacing between label and text is too big
- [x] Homescreen: Portfolio balance - less spacing from the top
- [x] Graph: Focus state label is to tall - probably spacing?
- [x] Homescreen: Spacing between porfolio balance and graph is too big
- [x] Homescreen: portfolio balance label should not have shadow
- [ ] Header when scrollin - when scrolling, header should have line
- [x] Receive: remove "change" when going from asset detail to Receive
- [x] Receive: revealed QR code - icons in sharing and copying buttons re not aligned with label
- [x] FAQ: Click on "+" does not expand the accordion
- [x] Asset list: If there are two assets from same coin, there is strange outline
- [x] Broken Receive screen Android Nokia - overlapped items
```

**Comment by bosomt** [comment]
**QA OK**

3abc6cf - [develop] - chore(suite-native): downgrade skia to v.0.1.202 (#9408)
