### ISSUE TITLE
Discovery 3. - optimize discovery process

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9464]
The discovery is very resource-demanding and makes the mobile app sluggish. With every found account, the portfolio graph is updated and there are dozens of fiat rate requests. There are probably also other bottlenecks that might make the discovery smoother. 

## TODO:
- [ ] inspect the app performance and identify the main performance problems
- [ ] extend this issue with the found insights and proposed solution (batching the fiat rates requests, hiding the portfolio graph during discovery, etc.)
- [ ] implement the proposed solution
