### ISSUE TITLE
[EPIC] Access Passphrase

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9653]
As a user I would like to be able to access my Passphrase wallet in order to be able to manage it. 

Highlevel acceptance criteria:
**Open passphrase**
User can open the passphrase via device switcher
Passphrase is triggered by user, not by connecting the trezor in order to avoid users to access it accidentally
When user clicks on Open passphrase, he is informed about basics. User can open link with article dedicated to Passphrase

**Enter passphrase on mobile screen**
User can enter passphrase on mobile screen.
When user taps into the input field, content is squeezed and user is focused only on entering the passphrase
When user enter passphrase and click confirm, he is prompt to Continue on Trezor device
When user press cancel, he is redirected back to previous screen and he can insert the passphrase again
When user confirms passphrase on Trezor device, discovery starts
When there are some transactions on the passphrase, user is redirected to dashboard
When the passphrase is empty, user is asked if he is opening known empty passphrase or whether he made typo
If user clicks on Open empty passphrase he gets information about what to do with Passphrase
Then user inserts the passphrase again to confirm it
User is prompt to confirm the passphrase on trezor device
When user confirms the passphrase on Trezor device, he is redirected to empty passphrase wallet dashboard
If user typed passphrase which does match with the first entered passphrase, he is informed that there is a mismatch and he has to start all over again 

**Enter passphrase on Trezor device** 
It is possible to enter Passphrase on device on TT, TS3 and further devices
When user enters and confirms passphrase on device, discovery starts
When there are some transactions on the passphrase, user is redirected to dashboard
If the passphrase is empty, user is prompt to confirm it again on Trezor device

**Passphrase mismatch**
If there is a mismatch in first typed passphrase and second (when user confirms the empty passphrase), user is informed. 
User must start the process of opening all over again

User can switch between standard and passphrase wallet when passphrase wallet is opened
User can set passphrase wallet to view-only

https://www.figma.com/file/mmDnYtctfjnreWhTjLfeQH/Passphrase?type=design&node-id=911-48773&mode=design&t=TLzwBFP7RNxuSMHY-4

```[tasklist]
### First iteration
- [ ] https://github.com/trezor/trezor-suite/issues/11553
- [ ] https://github.com/trezor/trezor-suite/issues/11979
- [ ] https://github.com/trezor/trezor-suite/issues/11964
- [ ] https://github.com/trezor/trezor-suite/issues/11938
- [ ] https://github.com/trezor/trezor-suite/issues/11469
- [ ] https://github.com/trezor/trezor-suite/issues/11470
- [ ] https://github.com/trezor/trezor-suite/issues/11752
- [ ] https://github.com/trezor/trezor-suite/issues/12132
- [ ] https://github.com/trezor/trezor-suite/issues/12131
- [ ] Handle bad internet connection leading to nothing found
- [ ] https://github.com/trezor/trezor-suite/issues/12207
```

```[tasklist]
### Second iteration
- [ ] https://github.com/trezor/trezor-suite/issues/11972
- [ ] https://github.com/trezor/trezor-suite/issues/11973
- [ ] https://github.com/trezor/trezor-suite/issues/11974
- [ ] https://github.com/trezor/trezor-suite/issues/11468
- [ ] https://github.com/trezor/trezor-suite/issues/12176
```

**Comment by mnuky** [comment]
closing - we no longer work with issues as Epic. Content moved to: https://github.com/trezor/trezor-suite/milestone/55
