### ISSUE TITLE
[EPIC] Add new coin/account

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9654]
User can add new coin or create new account in the app. 

**1. Via My asset screen**

**Acceptance criteria:**
_**Add new coin:**_
1. When user wants to add new coin to be in the app, he can create it via "+" button on My asset page
2. When user clicks on the "+" he can choose from available coins for the connected device
3. When user chooses coin which has more  account types we let him choose

_**Add new account:**_
1. When user wants to add new coin to be in the app, he can create it via "+" button on My asset page
2. When user clicks on the "1" he can choose from available coins for the connected device
3. When user chooses coin which already has one account, we add new account
BTC like coins - user must choose account type
ETH like coins - user does not need to choose the account type
4. User can’t create new account if the previous one has no transactions
5. Maximum number of accounts under one coin is 10

**2. Via Receive**
**Acceptance criteria**
1. When user clicks on Receive, he sees available coins with active accounts
2. User can click on (+) and sees all available coins
3. If user chooses coin and type we activate the coin (add coin) on his behalf
4. User continues to receive address verification
5. When user leaves the Receive address flow and comes back to My assets, he sees new account activated

**Available coins per devices:**
**T-One:** Bitcoin, Ethereum (+tokens), Litecoin, Ethereum Classic, Bitcoin Cash, Bitcoin Gold, Dash, DigiByte, Dogecoin, Namecoin, Vertcoin, Zcash + testnet coins (if enabled) Bitcoin Testnet, Bitcoin Regtest, Ethereum Goerli
**TT:** Bitcoin, Ethereum (+tokens), Litecoin, Ethereum Classic, Bitcoin Cash, Bitcoin Gold, Dash, DigiByte, Dogecoin, Namecoin, Vertcoin, Zcash, Cardano, XRP + testnet coins (if enabled) Bitcoin Testnet, Bitcoin Regtest, Ethereum Goerli, XRP Testnet, Cardano Testnet
**TS3:** BTC, Ethereum (+tokens), Litecoin, Ethereum Classic, Bitcoin Cash, Dogecoin, Zcash, Cardano, XRP + testnet coins (if enabled) Bitcoin Testnet, Bitcoin Regtest, Ethereum Goerli, XRP Testnet, Cardano Testnet

**Coins with account types option:**
Bitcoin: Segwit (default type), Taproot, Legacy Segwit, Legacy
Litecoin: SegWit (default type), Legacy SegWit, Legacy
Bitcoin Gold: Legacy SegWit (default type), Legacy
DigiByte: Legacy SegWit default type), Legacy
Vertcoin: SegWit (default type), Legacy SegWit, Legacy

https://www.figma.com/file/BVA3IAmqDjz36sBGVtEFbz/Add-new-coin-%2F-Account?type=design&node-id=280-18973&mode=design&t=ngbJJ2Lc1IHukoMt-0

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/11295
- [ ] https://github.com/trezor/trezor-suite/issues/10675
- [ ] https://github.com/trezor/trezor-suite/issues/10676
- [ ] https://github.com/trezor/trezor-suite/issues/10677
- [ ] https://github.com/trezor/trezor-suite/issues/10870
- [ ] https://github.com/trezor/trezor-suite/issues/10827
- [ ] https://github.com/trezor/trezor-suite/issues/11317
- [ ] https://github.com/trezor/trezor-suite/issues/11104
- [ ] https://github.com/trezor/trezor-suite/issues/11533
```

**Comment by bosomt** [comment]
**QA OK**

24.4.0 (74)
Last commit hash: 2882f42525f5173c6673e0b4c41c9644c2ccb92e

**Comment by matejkriz** [comment]
Closing as done ✅
