### ISSUE TITLE
[EPIC] Send coins

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9735]
> 🚧 WIP: This EPIC acceptance criteria is still in progress

As a user I would like to be able to send coins via mobile app in order to be able to manage my funds.

1. Send Bitcoin
2. Send Ethereum + tokens
3. Send Cardano
4. Send XRP
6. Other coins
```[tasklist]
### Technical Tasks 🔩
- [ ] https://github.com/trezor/trezor-suite/issues/11072
- [ ] https://github.com/trezor/trezor-suite/issues/11073
- [ ] https://github.com/trezor/trezor-suite/issues/10822
- [ ] https://github.com/trezor/trezor-suite/issues/12027
- [ ] https://github.com/trezor/trezor-suite/issues/12094
- [ ] https://github.com/trezor/trezor-suite/issues/10823
- [ ] https://github.com/trezor/trezor-suite/issues/10867
- [ ] https://github.com/trezor/trezor-suite/issues/10868
- [ ] https://github.com/trezor/trezor-suite/issues/10871
- [ ] https://github.com/trezor/trezor-suite/issues/10872
- [ ] https://github.com/trezor/trezor-suite/issues/10873
- [ ] https://github.com/trezor/trezor-suite/issues/10866
- [ ] https://github.com/trezor/trezor-suite/issues/10953
- [ ] Send coins - analytic events
```

```[tasklist]
### UI/UX Tasks 👩‍🎨
- [ ] WIP 🚧: Issues will be created when there is a UI/UX design ready
```

**Comment by mnuky** [comment]
closing - we no longer work with issues as Epics, we use Milestones instead. Content moved to: https://github.com/trezor/trezor-suite/milestone/40
