### ISSUE TITLE
Connected Trezor issues

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9887]
```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/9928
- [ ] https://github.com/trezor/trezor-suite/issues/9965
- [x] Receive: With connected Trezor T, address was not displayed on Trezor device - so I could not confirm - watch the video (2:01) ( Fixed by [#9987](https://github.com/trezor/trezor-suite/pull/9987#event-11003613171))
- [x] Mixed accounts when switching devices: Connect Trezor T and load the assets > Disconnect > Connect Trezor One > There are assets from Trezor T > Disconnect Trezor One > Connect again Trezor T. Fixed by: [#9937](https://github.com/trezor/trezor-suite/pull/9937/files)
- [ ] https://github.com/trezor/trezor-suite/issues/9929
- [ ] https://github.com/trezor/trezor-suite/issues/10086
```

Videos:
https://drive.google.com/file/d/1QyfYoSOFXH8plVlA90JMk4eQio0DYPom/view?usp=sharing
https://drive.google.com/file/d/1icz35YYoN_dIorgxA8TwAwCAKCYGFnyH/view?usp=sharing

**Connect&Unlock**
Bottom menu bug:
![Image](https://github.com/trezor/trezor-suite/assets/84183817/a111d378-49cd-4160-963c-e438ea084694)

**Discovery**
When the discovery starts, user should never see the message "There are no coins discovered" - it should go straightly to loading skeleton and then if we don't find any assets, display "There are no coins discovered"
![Image](https://github.com/trezor/trezor-suite/assets/84183817/f76adf02-6d9f-4370-b034-d0e67a0d7a9a)
